### ISSUE TITLE
Feature: setup codecov

### ISSUE THREAD

**Issue by vadimalekseev** [ozontech/file.d#196]

**Comment by vadimalekseev** [comment]
@sashamelentyev already started doing it: https://github.com/vadimalekseev/file.d/blob/196-setup-covecov/.github/workflows/codecov.yml :)

it's not a problem to inject the config. The problem is to find people with full rights who could enable the bot in the repository

**Comment by sashamelentyev** [comment]
@vadimalekseev good. Thank you!

**Comment by vadimalekseev** [comment]
@sashamelentyev, if you want to help you can take this: https://github.com/ozontech/file.d/issues/200
