### ISSUE TITLE
CI: Go 1.21.0 + default.pgo

### ISSUE THREAD

**Issue by vadimalekseev** [ozontech/file.d#468]
Bump Go 1.21.0 and paste `default.pgo` to enable pgo

**Comment by zamazan4ik** [comment]
@vadimalekseev Do you have performance benefits numbers from enabling PGO on file.d? If yes, could you please share the measured performance numbers? Another question - from which workload is the `default.pgo` file collected? We are trying to estimate - Do we need to prepare our own PGO profile or we can use the distributed with file.d one?

Thanks in advance!
