### ISSUE TITLE
Feature: Add new plugin

### ISSUE THREAD

**Issue by kirillov6** [ozontech/file.d#563]
Add a new plugin that will replace multiple UTF-8-encoded bytes with corresponding characters. Support unicode (`\u...` and `\U...`), hex (`\x...`) and octal (`\{0-3}{0-7}{0-7}`).

For example, `\xD0\xA1\xD0\x98\xD0\xA1\xD0\xA2\xD0\x95\xD0\x9C\xD0\x90.xml` -> `СИСТЕМА.xml`.

**Comment by Anasstozir** [comment]
Hy
