### ISSUE TITLE
Feature: add elasticsearch authentication support

### ISSUE THREAD

**Issue by dmitry-ee** [ozontech/file.d#89]
**Is your feature request related to a problem? Please describe.**
Would like to test `file.d`, but as i see, it's not supporting any kind of authentication for elasticsearch

**Describe the solution you'd like**
[Filebeat authentication solution](https://github.com/elastic/beats/blob/2b26691e0c4b90955e75238eea2d4e9db7e69942/libbeat/outputs/elasticsearch/docs/elasticsearch.asciidoc) is totally fine

Cheers!
Looking forward for any comments from your side

**Comment by ssnd** [comment]
Hello Dmitry! 
Thanks a lot for your feature request! 

Yes, file.d doesn't support ES authentication for now. 

We have discussed this issue internally and concluded that ES auth is a really important feature to add.
The feature is now in our backlog and we'll start working on this as soon as possible.

Unfortunately, I'm not ready to give you an estimate on the timeframes, but we will keep you posted on this issue!

You are also welcome to contribute to file.d yourself, it would be a great help for the team of maintainers.
In case you want to contribute, please let us know, we'll be happy to assist you in any possible way.

Regards

**Comment by ssnd** [comment]
@dmitry-ee done :-)
